import java.util.ArrayList;

public class Animal {
    protected int id;
    protected String name;
    protected String species;
    protected String birthDate;
    protected String adoptionPrice;
    protected String owner;
    protected ArrayList<String> traits;

	/*
	Identifiers for animals are automatically generated by the auto-increment feature provided by SQL.
	Traits and species are NOT predefined, users may provide any they wish.
	*/

    public Animal() {
    }

    public Animal(int id) {
        this.id = id;
    }

    public Animal(int id, String name, String species, String birthDate, String adoptionPrice) {
        this(name, species, birthDate, adoptionPrice);
        this.id = id;
    }

    public Animal(String name, String species, String birthDate, String adoptionPrice) {
        this.name = name;
        this.species = species;
        this.birthDate = birthDate;
        this.adoptionPrice = adoptionPrice;
        // this.traits = ArrayList<>;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSpecies() {
        return species;
    }

    public void setSpecies(String species) {
        this.species = species;
    }

    public String getBirthDate() {
        return birthDate;
    }

    public void setBirthDate(String birthDate) {
        this.birthDate = birthDate;
    }

    public String getAdoptionPrice() {
        return adoptionPrice;
    }

    public void setAdoptionPrice(String adoptionPrice) {
        this.adoptionPrice = adoptionPrice;
    }

    public String getOwner(){
        return owner;
    }
    public void setOwner(){
        this.owner=User.getUsername();
    }

}// end [ CLASS: Animal ]
