package Database_TermProject;

//------------------------------------------------------------------------------------------------------//
// Notes:                                                                                               //
//      - Attributes: Unique identifier, name, species, birthdate, adoption price and list of           //
//              personality traits (where each trait is a single lower-case word)                       //
//      - Once adopted an animal is removed from the database                                           //
//      - An animal may have any number of reviews (including none)                                     //
//      - Identifiers for animals auto-generated by the auto-increment feature provided by SQL          //
//      - Traits and species are NOT predefined,users may provide any they wish                         //
//------------------------------------------------------------------------------------------------------//

public class Animal {
	protected int id;
	protected String name;
	protected String species;
	protected String birthDate;
	protected int adoptionPrice;
	protected String ownerUsername;
	
	public Animal() {
	}
	
	public Animal(int id) {
		this.id = id;
	}
	
	public Animal(int id, String name, String species, String birthDate, int adoptionPrice, String ownerUsername) {
	    this(name, species, birthDate, adoptionPrice, ownerUsername);
		this.id = id;
	}
	
	public Animal(String name, String species, String birthDate, int adoptionPrice, String ownerUsername) {

        // Invoked when a NEW animal is being added
        // Variable "id" is auto-assigned when preparedStatement is executed [ See: AnimalDAO.insert() ]

        this.name = name;
		this.species = species;
		this.birthDate = birthDate;
		this.adoptionPrice = adoptionPrice;
		this.ownerUsername = ownerUsername;
	}

	public int getId() {
		return id;
	}
	
	public void setId(int id) {
		this.id = id;
	}
	
	public String getName() {
		return name;
	}
	
	public void setName(String name) {
		this.name = name;
	}
	
	public String getSpecies() {
		return species;
	}
	
	public void setSpecies(String species) {
		this.species = species;
	}
	
	public String getBirthDate() {
		return birthDate;
	}
	
	public void setBirthDate(String birthDate) {
		this.birthDate = birthDate;
	}
	
	public int getAdoptionPrice() {
		return adoptionPrice;
	}
	
	public void setAdoptionPrice(int adoptionPrice) {
        //int adoptionPrice_toInt = Integer.parseInt(adoptionPrice);
	    this.adoptionPrice = adoptionPrice;
	}

    public String getOwnerUsername() { return ownerUsername; }

    public void setOwnerUsername(String ownerUsername) { this.ownerUsername = ownerUsername; }

}// end [ CLASS: Animal ]