package Database_TermProject;

//------------------------------------------------------------------------------------------------------//
// Notes:                                                                                               //
//      - Attributes: Unique identifier, name, species, birthdate, adoption price and list of           //
//              personality traits (where each trait is a single lower-case word)                       //
//      - Once adopted an animal is removed from the database                                           //
//      - An animal may have any number of reviews (including none)                                     //
//      - Identifiers for animals auto-generated by the auto-increment feature provided by SQL          //
//      - Traits and species are NOT predefined,users may provide any they wish                         //
//------------------------------------------------------------------------------------------------------//

public class Review {
	protected int id;
	protected int animalID;
    protected String authorUsername;
	protected String rating;
	protected String comment;
	
	public Review() {
	}

    public Review(int id, int animalID, String authorUsername, String rating, String comment) {
        this(animalID, authorUsername, rating, comment);
        this.id = id;
    }

	public Review(int animalID, String authorUsername, String rating, String comment) {
        this.animalID = animalID;
		this.authorUsername = authorUsername;
		this.rating = rating;
		this.comment = comment;
	}

    public void setReviewID(int id) {
	    this.id = id;
	}

	public int getReviewID() {
	    return id;
	}

    public void setId(int id) {
        this.id = id;
    }

    public int getAnimalID() {
	    return animalID;
	}

    public void setAnimalID(int animalID) {
        this.animalID = animalID;
    }

    public String getAuthorUsername() {
        return authorUsername;
    }

    public void setAuthorUsername(String authorUsername) {
        this.authorUsername = authorUsername;
    }

    public String getRating() {
        return rating;
    }

    public void setRating(String rating) {
        this.rating = rating;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

}// end [ CLASS: Review ]