import java.util.ArrayList;

//------------------------------------------------------------------------------------------------------//
// Notes:                                                                                               //
//      - Attributes: Unique identifier, name, species, birthdate, adoption price and list of           //
//              personality traits (where each trait is a single lower-case word)                       //
//      - Once adopted an animal is removed from the database                                           //
//      - An animal may have any number of reviews (including none)                                     //
//      - Identifiers for animals auto-generated by the auto-increment feature provided by SQL          //
//      - Traits and species are NOT predefined,users may provide any they wish                         //
//------------------------------------------------------------------------------------------------------//

public class Animal {
	protected int id;
	protected String name;
	protected String species;
	protected String birthDate;
	protected String adoptionPrice;
	protected String owner;
	//protected ArrayList<String> traits;
    protected String traits;
	
	public Animal() {
	}
	
	public Animal(int id) {
		this.id = id;
	}
	
	public Animal(int id, String name, String species, String birthDate, String adoptionPrice, String traits) {
		this(name, species, birthDate, adoptionPrice, traits);
		this.id = id;
	}
	
	public Animal(String name, String species, String birthDate, String adoptionPrice, String traits) {

        // Invoked when a NEW animal is being added
        // Variable "id" is auto-assigned when preparedStatement is executed [ See: AnimalDAO.insert() ]

	    this.name = name;
		this.species = species;
		this.birthDate = birthDate;
		this.adoptionPrice = adoptionPrice;
		// this.traits = ArrayList<>;
        this.traits = traits;
	}
	
	public int getId() {
		return id;
	}
	
	public void setId(int id) {
		this.id = id;
	}
	
	public String getName() {
		return name;
	}
	
	public void setName(String name) {
		this.name = name;
	}
	
	public String getSpecies() {
		return species;
	}
	
	public void setSpecies(String species) {
		this.species = species;
	}
	
	public String getBirthDate() {
		return birthDate;
	}
	
	public void setBirthDate(String birthDate) {
		this.birthDate = birthDate;
	}
	
	public String getAdoptionPrice() {
		return adoptionPrice;
	}
	
	public void setAdoptionPrice(String adoptionPrice) {
		this.adoptionPrice = adoptionPrice;
	}

    public String getOwner() { return owner; }

    public void setOwner(String usernameOfOwner) { this.owner = usernameOfOwner; }

}// end [ CLASS: Animal ]