import java.util.ArrayList;

//---------------------------------------------------------------------------------------------------------//
// Note:                                                                                                   //
//    Identifiers for animals are automatically generated by the auto-increment feature provided by SQL    //
//    Traits and species are NOT predefined,users may provide any they wish.                               //
//---------------------------------------------------------------------------------------------------------//

public class User {
    protected int id;
    protected String username;
    protected String password;
    protected String firstName;
    protected String lastName;
    protected String email;

    // TODO: Confirm or change posted-animal recording method
    protected ArrayList<Animal> myPostedAdoptions;
    protected int postedAdoptionsCount = 0;
 
    public User() {
    }
 
    public User(int id) {
        this.id = id;
    }

    // TODO: Remove this constructor (Then: Update initialization of root user in InitDB to reflect constructor edit)
    public User(String username, String password){
        this.username = username;
        this.password = password;
    }
 
    public User(int id, String username, String password, String firstName, String lastName, String email) {
        this(username, password, firstName, lastName, email);
        this.id = id;
    }

    public User(String username, String password, String firstName, String lastName, String email) {

        // Invoked when NEW user is being added
        // Variable "id" is auto-assigned when preparedStatement is executed [ See: UserDAO.insert() ]

        this.username = username;
        this.password = password;
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
    }
 
    public int getId() {
        return id;
    }
 
    public void setId(int id) {
        this.id = id;
    }
    
    public String getUsername() { return username; }
    
    public void setUsername(String username) { this.username = username; }
    
    public String getPassword() { return password; }
    
    public void setPassword(String password) { this.password = password; }
    
    public String getFirstName() { return firstName; }
    
    public void setFirstName(String firstName) { this.firstName = firstName; }
    
    public String getLastName() { return lastName; }
    
    public void setLastName(String lastName) { this.lastName = lastName; }
    
    public String getEmail() { return email; }
    
    public void setEmail(String email) { this.email = email; }

    public boolean maxPostsReached() { return postedAdoptionsCount >= 5; }

    public void addNewAnimalToMyPostedAnimals(Animal animal){
        myPostedAdoptions.add(animal);
        postedAdoptionsCount++;
    }
    
}// end [ CLASS: User ]